// Worker capabilities served on /dan/capabilities/1.0.0 (one request, one reply,
// uvarint-length-delimited, like libp2p's own identify protocol).
//
// Regenerate: protoc --go_out=. --go_opt=paths=source_relative capabilities/capabilities.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: capabilities/capabilities.proto

package capabilities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_STATE_OFFLINE   State = 0 // no fresh status from the worker
	State_STATE_AVAILABLE State = 1
	State_STATE_RESERVED  State = 2
	State_STATE_LOADING   State = 3
	State_STATE_SERVING   State = 4
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_OFFLINE",
		1: "STATE_AVAILABLE",
		2: "STATE_RESERVED",
		3: "STATE_LOADING",
		4: "STATE_SERVING",
	}
	State_value = map[string]int32{
		"STATE_OFFLINE":   0,
		"STATE_AVAILABLE": 1,
		"STATE_RESERVED":  2,
		"STATE_LOADING":   3,
		"STATE_SERVING":   4,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_capabilities_capabilities_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_capabilities_capabilities_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_capabilities_capabilities_proto_rawDescGZIP(), []int{0}
}

type CapabilityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty asks about every model.
	ModelSha256   string `protobuf:"bytes,1,opt,name=model_sha256,json=modelSha256,proto3" json:"model_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityRequest) Reset() {
	*x = CapabilityRequest{}
	mi := &file_capabilities_capabilities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRequest) ProtoMessage() {}

func (x *CapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_capabilities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRequest.ProtoReflect.Descriptor instead.
func (*CapabilityRequest) Descriptor() ([]byte, []int) {
	return file_capabilities_capabilities_proto_rawDescGZIP(), []int{0}
}

func (x *CapabilityRequest) GetModelSha256() string {
	if x != nil {
		return x.ModelSha256
	}
	return ""
}

type Capability struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion  uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // 1
	WorkerId         string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RuntimeAbi       string                 `protobuf:"bytes,3,opt,name=runtime_abi,json=runtimeAbi,proto3" json:"runtime_abi,omitempty"`
	DataProtocols    []string               `protobuf:"bytes,4,rep,name=data_protocols,json=dataProtocols,proto3" json:"data_protocols,omitempty"` // "/dan/transport/1.0.0", "/dan/ring/1.0.0"
	Device           string                 `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`
	TotalMemoryMib   uint64                 `protobuf:"varint,6,opt,name=total_memory_mib,json=totalMemoryMib,proto3" json:"total_memory_mib,omitempty"`       // 0 when unknown
	OfferedMemoryMib uint64                 `protobuf:"varint,7,opt,name=offered_memory_mib,json=offeredMemoryMib,proto3" json:"offered_memory_mib,omitempty"` // what a planner may use
	MaxContext       uint32                 `protobuf:"varint,8,opt,name=max_context,json=maxContext,proto3" json:"max_context,omitempty"`
	MaxSessions      uint32                 `protobuf:"varint,9,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	Models           []*ModelAvailability   `protobuf:"bytes,10,rep,name=models,proto3" json:"models,omitempty"`
	State            State                  `protobuf:"varint,11,opt,name=state,proto3,enum=dan.capabilities.v1.State" json:"state,omitempty"`
	Assignment       *Assignment            `protobuf:"bytes,12,opt,name=assignment,proto3" json:"assignment,omitempty"` // set while not AVAILABLE
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_capabilities_capabilities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_capabilities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_capabilities_capabilities_proto_rawDescGZIP(), []int{1}
}

func (x *Capability) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Capability) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Capability) GetRuntimeAbi() string {
	if x != nil {
		return x.RuntimeAbi
	}
	return ""
}

func (x *Capability) GetDataProtocols() []string {
	if x != nil {
		return x.DataProtocols
	}
	return nil
}

func (x *Capability) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Capability) GetTotalMemoryMib() uint64 {
	if x != nil {
		return x.TotalMemoryMib
	}
	return 0
}

func (x *Capability) GetOfferedMemoryMib() uint64 {
	if x != nil {
		return x.OfferedMemoryMib
	}
	return 0
}

func (x *Capability) GetMaxContext() uint32 {
	if x != nil {
		return x.MaxContext
	}
	return 0
}

func (x *Capability) GetMaxSessions() uint32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *Capability) GetModels() []*ModelAvailability {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Capability) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_OFFLINE
}

func (x *Capability) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type ModelAvailability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Layers        uint32                 `protobuf:"varint,2,opt,name=layers,proto3" json:"layers,omitempty"`
	Hidden        uint32                 `protobuf:"varint,3,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Cached        []*Range               `protobuf:"bytes,4,rep,name=cached,proto3" json:"cached,omitempty"` // hint only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelAvailability) Reset() {
	*x = ModelAvailability{}
	mi := &file_capabilities_capabilities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelAvailability) ProtoMessage() {}

func (x *ModelAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_capabilities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelAvailability.ProtoReflect.Descriptor instead.
func (*ModelAvailability) Descriptor() ([]byte, []int) {
	return file_capabilities_capabilities_proto_rawDescGZIP(), []int{2}
}

func (x *ModelAvailability) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ModelAvailability) GetLayers() uint32 {
	if x != nil {
		return x.Layers
	}
	return 0
}

func (x *ModelAvailability) GetHidden() uint32 {
	if x != nil {
		return x.Hidden
	}
	return 0
}

func (x *ModelAvailability) GetCached() []*Range {
	if x != nil {
		return x.Cached
	}
	return nil
}

type Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Begin         uint32                 `protobuf:"varint,1,opt,name=begin,proto3" json:"begin,omitempty"`
	End           uint32                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_capabilities_capabilities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_capabilities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_capabilities_capabilities_proto_rawDescGZIP(), []int{3}
}

func (x *Range) GetBegin() uint32 {
	if x != nil {
		return x.Begin
	}
	return 0
}

func (x *Range) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	ModelSha256   string                 `protobuf:"bytes,2,opt,name=model_sha256,json=modelSha256,proto3" json:"model_sha256,omitempty"`
	Begin         uint32                 `protobuf:"varint,3,opt,name=begin,proto3" json:"begin,omitempty"`
	End           uint32                 `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_capabilities_capabilities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_capabilities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_capabilities_capabilities_proto_rawDescGZIP(), []int{4}
}

func (x *Assignment) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *Assignment) GetModelSha256() string {
	if x != nil {
		return x.ModelSha256
	}
	return ""
}

func (x *Assignment) GetBegin() uint32 {
	if x != nil {
		return x.Begin
	}
	return 0
}

func (x *Assignment) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

var File_capabilities_capabilities_proto protoreflect.FileDescriptor

const file_capabilities_capabilities_proto_rawDesc = "" +
	"\n" +
	"\x1fcapabilities/capabilities.proto\x12\x13dan.capabilities.v1\"6\n" +
	"\x11CapabilityRequest\x12!\n" +
	"\fmodel_sha256\x18\x01 \x01(\tR\vmodelSha256\"\x83\x04\n" +
	"\n" +
	"Capability\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vruntime_abi\x18\x03 \x01(\tR\n" +
	"runtimeAbi\x12%\n" +
	"\x0edata_protocols\x18\x04 \x03(\tR\rdataProtocols\x12\x16\n" +
	"\x06device\x18\x05 \x01(\tR\x06device\x12(\n" +
	"\x10total_memory_mib\x18\x06 \x01(\x04R\x0etotalMemoryMib\x12,\n" +
	"\x12offered_memory_mib\x18\a \x01(\x04R\x10offeredMemoryMib\x12\x1f\n" +
	"\vmax_context\x18\b \x01(\rR\n" +
	"maxContext\x12!\n" +
	"\fmax_sessions\x18\t \x01(\rR\vmaxSessions\x12>\n" +
	"\x06models\x18\n" +
	" \x03(\v2&.dan.capabilities.v1.ModelAvailabilityR\x06models\x120\n" +
	"\x05state\x18\v \x01(\x0e2\x1a.dan.capabilities.v1.StateR\x05state\x12?\n" +
	"\n" +
	"assignment\x18\f \x01(\v2\x1f.dan.capabilities.v1.AssignmentR\n" +
	"assignment\"\x8f\x01\n" +
	"\x11ModelAvailability\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x16\n" +
	"\x06layers\x18\x02 \x01(\rR\x06layers\x12\x16\n" +
	"\x06hidden\x18\x03 \x01(\rR\x06hidden\x122\n" +
	"\x06cached\x18\x04 \x03(\v2\x1a.dan.capabilities.v1.RangeR\x06cached\"/\n" +
	"\x05Range\x12\x14\n" +
	"\x05begin\x18\x01 \x01(\rR\x05begin\x12\x10\n" +
	"\x03end\x18\x02 \x01(\rR\x03end\"r\n" +
	"\n" +
	"Assignment\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12!\n" +
	"\fmodel_sha256\x18\x02 \x01(\tR\vmodelSha256\x12\x14\n" +
	"\x05begin\x18\x03 \x01(\rR\x05begin\x12\x10\n" +
	"\x03end\x18\x04 \x01(\rR\x03end*i\n" +
	"\x05State\x12\x11\n" +
	"\rSTATE_OFFLINE\x10\x00\x12\x13\n" +
	"\x0fSTATE_AVAILABLE\x10\x01\x12\x12\n" +
	"\x0eSTATE_RESERVED\x10\x02\x12\x11\n" +
	"\rSTATE_LOADING\x10\x03\x12\x11\n" +
	"\rSTATE_SERVING\x10\x04B\x1aZ\x18dan/sidecar/capabilitiesb\x06proto3"

var (
	file_capabilities_capabilities_proto_rawDescOnce sync.Once
	file_capabilities_capabilities_proto_rawDescData []byte
)

func file_capabilities_capabilities_proto_rawDescGZIP() []byte {
	file_capabilities_capabilities_proto_rawDescOnce.Do(func() {
		file_capabilities_capabilities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capabilities_capabilities_proto_rawDesc), len(file_capabilities_capabilities_proto_rawDesc)))
	})
	return file_capabilities_capabilities_proto_rawDescData
}

var file_capabilities_capabilities_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_capabilities_capabilities_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_capabilities_capabilities_proto_goTypes = []any{
	(State)(0),                // 0: dan.capabilities.v1.State
	(*CapabilityRequest)(nil), // 1: dan.capabilities.v1.CapabilityRequest
	(*Capability)(nil),        // 2: dan.capabilities.v1.Capability
	(*ModelAvailability)(nil), // 3: dan.capabilities.v1.ModelAvailability
	(*Range)(nil),             // 4: dan.capabilities.v1.Range
	(*Assignment)(nil),        // 5: dan.capabilities.v1.Assignment
}
var file_capabilities_capabilities_proto_depIdxs = []int32{
	3, // 0: dan.capabilities.v1.Capability.models:type_name -> dan.capabilities.v1.ModelAvailability
	0, // 1: dan.capabilities.v1.Capability.state:type_name -> dan.capabilities.v1.State
	5, // 2: dan.capabilities.v1.Capability.assignment:type_name -> dan.capabilities.v1.Assignment
	4, // 3: dan.capabilities.v1.ModelAvailability.cached:type_name -> dan.capabilities.v1.Range
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_capabilities_capabilities_proto_init() }
func file_capabilities_capabilities_proto_init() {
	if File_capabilities_capabilities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capabilities_capabilities_proto_rawDesc), len(file_capabilities_capabilities_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_capabilities_capabilities_proto_goTypes,
		DependencyIndexes: file_capabilities_capabilities_proto_depIdxs,
		EnumInfos:         file_capabilities_capabilities_proto_enumTypes,
		MessageInfos:      file_capabilities_capabilities_proto_msgTypes,
	}.Build()
	File_capabilities_capabilities_proto = out.File
	file_capabilities_capabilities_proto_goTypes = nil
	file_capabilities_capabilities_proto_depIdxs = nil
}
